### ISSUE TITLE
Controlling Audio

### ISSUE THREAD

**Issue by gitagogaming** [licht1stein/pyzoom#115]
Do you know if its possible to control the audio thru the zoom api?  I am looking to be able to mute my microphone and or other participants in the meeting  

I was looking at docs and could only find it in the SDK info.. If you have any knowledge of it please link it and I will see about doing a pull request with some updates

**Comment by licht1stein** [comment]
I don't think it's possible right now, see this discussion:

https://devforum.zoom.us/t/rest-api-to-mute-and-unmute-zoom-room/6137/12
