### ISSUE TITLE
Recommend not hard-coding the base-url so it can work with ZoomGov as well

### ISSUE THREAD

**Issue by ajilling** [licht1stein/pyzoom#133]
The `base_url` is set to `https://api.zoom.us/v2`. It would be nice to have a clean way of changing this to to `https://api.zoomgov.us/v2`

**Comment by licht1stein** [comment]
Here you go:

https://github.com/licht1stein/pyzoom#basic-instantiation

**Comment by ajilling** [comment]
Heyyyyyy thanks!
