### ISSUE TITLE
Can't seem to Create a meeting I get this error

### ISSUE THREAD

**Issue by slimergamer** [licht1stein/pyzoom#19]
in create_meeting
    return schemas.ZoomMeeting(**response.json())
  File "pydantic\main.py", line 346, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ZoomMeeting
registration_url
  field required (type=value_error.missing)

**Comment by payaldas0505** [comment]
I am also getting the same issue. Please help me if you found any solution.

**Comment by licht1stein** [comment]
It's quite simple to solve, sorry for late reply.

**Comment by licht1stein** [comment]
Ok, done. Fixed in version 0.1.7

**Comment by licht1stein** [comment]
@slimergamer @payaldas0505
