### ISSUE TITLE
Error handling fails when Zoom API returns non-JSON response

### ISSUE THREAD

**Issue by thibaudcolas** [licht1stein/pyzoom#70]
👋  I’ve been using this client on a project and overall really like it. Hit a snag with Zoom’s error handling though.

In the error handling code here: https://github.com/licht1stein/pyzoom/blob/59cc597ce89c9e3dee621caa318ad1a20d8db632/pyzoom/_base.py#L48-L55

The client assumes the Zoom API will return valid JSON. This raised a `JSONDecodeError` for me. This can be reproduced by using `create_meeting` and providing a password longer than 10 characters – which Zoom doesn’t support.

**Comment by licht1stein** [comment]
Hi @thibaudcolas 

You can submit a PR that would do a password validation before sending it off to the API, if I correctly understand the issue

**Comment by thibaudcolas** [comment]
Hey @licht1stein, thank you for looking into this! Yes, fixing the password length should be no problem, and I’ll do this in my own code.

I don’t think my initial description was clear enough – the problem I’m reporting is that the error handling code I linked to fails completely when Zoom returns a non-JSON response. On line 49, a JSONDecodeError is raised, which is unhandled, so I don’t get to see any of the error logging from line 53 onwards.

The change I was thinking of to address this is to capture `JSONDecodeError`, and in this case display the full response with the `requests` API to display the raw response body.

**Comment by licht1stein** [comment]
That sounds like a good idea. Can you submit a PR?

**Comment by thibaudcolas** [comment]
I gave it a shot here: #71.
