### ISSUE TITLE
Add Users Component

### ISSUE THREAD

**Issue by antonylucisano** [licht1stein/pyzoom#93]
@licht1stein , hey, I've already created a "Users Component" for the _client.py for this project and tested against some work I've already done. 

Please could you give me access to create a PR/Branch for this repo and I'm currently unable to push up. 

Let me know if this isn't possible and I can send you over my changes instead

Thanks
Antony

**Comment by licht1stein** [comment]
Hi @antonylucisano!

Sorry for late reply. You don't need any special rights to do a PR. What you need to do, is fork the repo, and then once you commited your changes to the forked repo, you can do a PR from the fork to here.

Let me know if you need help with it.

**Comment by antonylucisano** [comment]
PR here: https://github.com/licht1stein/pyzoom/pull/96

**Comment by licht1stein** [comment]
#96
